version: 2.1
workflows:
  test_apps:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: sisisin/try-vt-ci:20181012-142742

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: git diff --exit-code # check yarn.lock diff
      - run: yarn test
      - run: yarn test-visual
